spring.application.name=Laboration1-AI
fallback.url=https://openrouter.ai/
resilience4j.circuitbreaker.instances.openRouterService.sliding-window-size=5
resilience4j.circuitbreaker.instances.openRouterService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.openRouterService.failure-rate-threshold=50
# Hur länge den ska vara i OPEN state innan den försöker igen
resilience4j.circuitbreaker.instances.openRouterService.wait-duration-in-open-state=10s
resilience4j.retry.instances.openRouterService.max-attempts=3
resilience4j.circuitbreaker.circuitBreakerAspectOrder=1
resilience4j.retry.retryAspectOrder=2

openrouter.api.model=openai/gpt-oss-120b:free
# google/gemma-4-31b-it:free
# openrouter/owl-alpha